/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PreviewRouteImport } from './pages/_app/preview'
import { Route as HomeRouteImport } from './pages/_app/home'
import { Route as EditorRouteImport } from './pages/_app/editor'

const PreviewRoute = PreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => rootRouteImport,
} as any)


export interface FileRoutesByFullPath {
    '/editor': typeof EditorRoute
    '/home': typeof HomeRoute
    '/preview': typeof PreviewRoute
}
export interface FileRoutesByTo {
    '/editor': typeof EditorRoute
    '/home': typeof HomeRoute
    '/preview': typeof PreviewRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/editor': typeof EditorRoute
    '/home': typeof HomeRoute
    '/preview': typeof PreviewRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/editor' | '/home' | '/preview'
    fileRoutesByTo: FileRoutesByTo
    to: '/editor' | '/home' | '/preview'
    id: '__root__' | '/editor' | '/home' | '/preview'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    EditorRoute: typeof EditorRoute
    HomeRoute: typeof HomeRoute
    PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/preview': {
            id: '/preview'
            path: '/preview'
            fullPath: '/preview'
            preLoaderRoute: typeof PreviewRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/home': {
            id: '/home'
            path: '/home'
            fullPath: '/home'
            preLoaderRoute: typeof HomeRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/editor': {
            id: '/editor'
            path: '/editor'
            fullPath: '/editor'
            preLoaderRoute: typeof EditorRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    EditorRoute: EditorRoute,
    HomeRoute: HomeRoute,
    PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
